### ISSUE TITLE
6.0.0 breaking change?

### ISSUE THREAD

**Issue by goodhyun** [meedan/react-native-share-menu#195]
Was there any breaking change on 6.0.0? 
Upgrading npm broke my code specifically on iOS, and had to roll back to 5.0.5.

**Comment by kubik369** [comment]
I am also getting an error coming from this package:
```
../app/node_modules/react-native-share-menu/ios/ReactShareViewController.swift:16:8: No exact matches in call to instance method 'jsBundleURL'
```
Currently investigating as I have updated multiple packages, so I am not sure whether it is due to the react update or only this package :)

**Comment by visoft** [comment]
I'm seeing the same error as @kubik369 when trying to add a custom share view.

**Comment by kubik369** [comment]
I was able to find the issue here [react-native 0.68 release notes](https://reactnative.dev/blog/2022/03/30/version-068#breaking-changes-and-version-bumps) - the `fallbackResource` parameter has been removed in this release.

It can be solved by removing the `fallbackResource` parameter from the `ReactShareViewController.swift` file and I also removed it from `AppDelegate.m` file. My app compiled afterwards, however, I got a generic react-hook/mismatch error, so I am presuming I have problems with some other dependencies. Could you please check whether the fix helps you, @visoft? :)

**Comment by visoft** [comment]
I'm having an issue with just getting callbacks for iOS shares. I don't really need a custom share view. It works perfectly on Android. But on iOS `handleShare` is never called. I've been looking at various issues and I think my config is correct, but alas no share notifications besides the initial call (`ShareMenu.getInitialShare`).

**Comment by visoft** [comment]
Update: I have callbacks working now on both iOS and Android. I used my full bundle id for the URL scheme and made that my group id for both the app and the share extension. The default share sheet accepts text but that's not coming through, just the image I'm sharing. I was expecting the text to show up. I have `NSExtensionActivationSupportsText` enabled. Is there something else I have to set to get the text that the user entered?
