### ISSUE TITLE
ShareExtension Memory Limit Exceeded Error when Sharing Content from Hebrew Applications

### ISSUE THREAD

**Issue by RDR96** [meedan/react-native-share-menu#256]
# Issue Description:

I am facing an issue while sharing content to my application using the react-native-share-menu library. I have implemented a custom popup with a JSX-based view to handle the sharing functionality. The content shared to my application usually comes from news apps, which include two attachments: a text attachment and a URL attachment.

Everything works fine except when I try to share content from applications that use Hebrew as their primary language. Strangely, when I share the content to my app, the popup opens as expected, but after a few seconds, an error occurs indicating that the memory limit assigned to the ShareExtension has been exceeded. This issue consistently arises when sharing from other Hebrew applications that contain two elements, as mentioned before: a Hebrew text (usually the news headline) and a URL pointing to the corresponding news article on the web.

I would appreciate any insights into what might be causing this issue or if there are any debugging techniques available to investigate the behavior of the ShareExtension when handling such data.

# Steps to Reproduce:

1- Install and launch the application.
2- Open any Hebrew news application that supports content sharing.
3- Select a news article and tap on the share button.
4- Choose the option to share the article to the previously installed application.
5- Observe that the custom popup appears correctly.
6- After a few seconds, an error message is displayed indicating that the ShareExtension has exceeded the memory limit.

# Expected Behavior:

The ShareExtension should handle the shared content from Hebrew applications without exceeding the memory limit and without causing any errors.

# Environment:

Library: react-native-share-menu
Library Version: 6.0.0
React Native Version: 0.71.11
Platform: iOS

# Additional Information:

- This only seem to happen in Hebrew apps that shares the url and the headline (which is in Hebrew).

**Comment by RDR96** [comment]
**I solved the issue.**

So the problem was the URL I was trying to share in my app. When you share a URL, the class `SLComposeServiceViewController` will open a default popup for previewing the content you share, which includes the URL. It attempts to retrieve data from the URL (such as an image preview) using a URL crawler. However, sometimes it fails to fetch the information from the URL and keeps trying until it runs out of memory.

One thing I noticed is that even if you create your own custom view to handle the data shared into your app, `SLComposeServiceViewController` will always create the default popup underneath. To address this, and especially if you're creating a custom view, I suggest replacing `SLComposeServiceViewController` with `SLComposeViewController` (which is in the `ShareViewController` class). Unlike `SLComposeServiceViewController`, `SLComposeViewController` does not provide a default popup.

**Comment by jb4e** [comment]
@RDR96 thank you so much for following up with the solution. This started happening for our extension recently. We think the problem might have gotten worse with ios 17, but we aren't 100% sure. Either way, switching to SLComposeViewController took our memory usage from 120MB+ to under 20MB.

**Comment by freethejazz** [comment]
@RDR96 I ran into an issue similar to this and your proposed fix worked like a charm. Thanks a ton!

One detail I'd add is that we noticed through profiling that our issue was not because of retries related to attempts to retrieve the data from the URL failing. Instead, we found that the entire page content was loaded, including images/scripts/css, and the memory needed to load those assets were being attributed to the share extension. As a result, sharing certain URLs which where light on resources did not initiate the crash, but pages with a lot of resources did.

@jb4e I also believe the problem got worse with iOS 17. Our share extension memory usage went from ~50MB on iOS 16 to 120MB+ on iOS 17. Through troubleshooting, we were able to confirm that the additional resources were being loaded on iOS 17 and not on iOS 16.

I believe, but have not confirmed, that the iOS team has added  a "feature" in iOS 17 that loads the shared URL eagerly, and that the memory required to eagerly load that URL is attributed to the share extension.
